version: '3.9'
services:
  llm-workflow-engine:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: lwe-container
    # restart: always
    volumes:
      - ./:/src
      - ./tmp:/tmp
      - ./Midata/config:/root/.config
      - ./Midata/data:/root/.local
    user: 1000:1000
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - EDITOR=vim
    command: "bash /src/docker-entrypoint.sh" # Run the entrypoint script
